"""
tests/test_nonregression_chao_u.py — Explicit non-regression gate for the
Chao-U richness estimator (V4).

Context: V4 reuses estimators/richness.py from V3 (locked). The only NEW
vectorization is `analysis.compute_entropy.richness_map` (box_sum per-window
Chao-U, used by Frontier+Richness in Phase 2). The user requires numerical
proof that:
  (1) V4's estimators/richness.py is bit-identical to V3's locked module,
  (2) the vectorized richness_map reproduces the locked scalar bias_cap
      per-window exactly (gap = 0) on many random knowledge states,
  (3) V4 Chao-U episodes reproduce the V3 reference CSV row-by-row
      (same seeds -> same steps_90 and alpha_sat_frac, gap = 0).
"""

import csv
import importlib.util
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np

from experiments._runner import run_episode
from utils.seed_manager import env_seed_for_run

V3_DIR = r"F:\Project6\uav_coverage_v3"

NONREG_RUNS = 5   # paired episodes checked against the live V3 code


def _load_v3_richness():
    spec = importlib.util.spec_from_file_location(
        "richness_v3", os.path.join(V3_DIR, "estimators", "richness.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _random_bundle(seed, n=40):
    rng = np.random.default_rng(seed)
    known = rng.random((n, n)) < 0.6
    obs = rng.random((n, n)) < 0.3
    obs &= known
    visit = rng.integers(0, 6, size=(n, n))
    total_unknown = int(np.sum((~known).astype(np.float64)))
    return visit, known, obs, total_unknown


def test_estimators_identical_to_v3():
    """(1) Same inputs -> identical outputs for every estimator/variant."""
    v4 = __import__("estimators.richness", fromlist=["richness"])
    v3 = _load_v3_richness()

    for seed in range(8):
        visit, known, obs, total_unknown = _random_bundle(seed)
        for variant in ("original", "cap", "bias", "bias_cap"):
            a = v4.chao_u(visit, known, obs, total_unknown, variant=variant)
            b = v3.chao_u(visit, known, obs, total_unknown, variant=variant)
            assert a == b, f"chao_u({variant}) differs at seed {seed}: {a} vs {b}"
        assert (v4.ace_u(visit, known, obs, total_unknown)
                == v3.ace_u(visit, known, obs, total_unknown))
        assert (v4.jackknife_u(visit, known, obs)
                == v3.jackknife_u(visit, known, obs))
        assert v4.total_known(known, obs) == v3.total_known(known, obs)
        assert np.array_equal(v4._frequency_counts(visit, known, obs),
                              v3._frequency_counts(visit, known, obs))


def test_vectorized_richness_map_equals_scalar_bias_cap():
    """(2) box_sum-based richness_map == scalar per-window bias_cap (gap=0)."""
    from analysis.compute_entropy import (_window_chao_u_scalar_sanity,
                                          richness_map)
    from estimators import richness as v4r

    for seed in range(6):
        visit, known, obs, total_unknown = _random_bundle(seed, n=25)
        for w in (1, 2, 5):
            fast = richness_map(visit, known, obs, w, total_unknown)
            ref = _window_chao_u_scalar_sanity(visit, known, obs, w,
                                               total_unknown)
            assert np.array_equal(fast, ref), \
                f"richness_map(w={w}, seed={seed}) != scalar bias_cap"
            # sanity: the reference really is the locked scalar estimator
            tr = known & ~obs
            ones = tr & (visit == 1)
            twos = tr & (visit == 2)
            F1, F2 = float(ones.sum()), float(twos.sum())
            assert abs(v4r.chao_u(visit, known, obs, total_unknown,
                                  variant="bias_cap")
                       - max(min((F1 * (F1 - 1)) / (2 * (F2 + 1)),
                                 float(total_unknown)), 1.0)) < 1e-9


def test_episodes_reproduce_v3_reference():
    """(3) V4 Chao-U episodes == live V3 code (same seeds) with gap = 0.

    NOTE: the historical V3 CSV (raw_comm_limited__Chao-U@bias_cap.csv) is
    STALE — it was generated by an older V3 commit (e.g. run 0: s90=3241).
    The current locked V3 code reproduces s90=2879 for run 0, identical to
    V4. The gate therefore compares V4 against the LIVE V3 module in a
    subprocess (avoids module-name collisions in the same interpreter).
    """
    if not os.path.isdir(V3_DIR):
        raise AssertionError(f"V3 project dir not found: {V3_DIR}")

    for r in range(NONREG_RUNS):
        v4 = run_episode("Chao-U", "comm_limited", r,
                         env_seed=env_seed_for_run(r),
                         fov_radius=5, K=0.5, grid_size=100, num_agents=6,
                         obstacle_ratio=0.05, max_steps=10000,
                         chao_variant="bias_cap", comm_range=5.0)
        v3 = _run_v3_episode(r)

        assert int(v4["steps_90"]) == v3["steps_90"], \
            f"run {r}: steps_90 {v4['steps_90']} != v3 {v3['steps_90']}"
        assert v4["censored"] == v3["censored"]
        assert abs(v4["alpha_sat_frac"] - v3["sat_frac"]) < 1e-12, \
            f"run {r}: sat_frac {v4['alpha_sat_frac']} != v3 {v3['sat_frac']}"
        assert int(v4["fusion_events"]) == v3["fus"], \
            f"run {r}: fusion_events {v4['fusion_events']} != v3 {v3['fus']}"
        assert abs(v4["final_coverage"] - v3["cov"]) < 1e-12, \
            f"run {r}: final_coverage {v4['final_coverage']} != v3 {v3['cov']}"


def _run_v3_episode(run_index):
    """Run ONE Chao-U episode through the live V3 code in a subprocess and
    return {steps_90, censored, sat_frac, fus, cov}."""
    import json
    import subprocess

    code = (
        "import sys, json; "
        f"sys.path.insert(0, r'{V3_DIR}'); "
        "from experiments._runner import run_episode; "
        "from utils.seed_manager import env_seed_for_run; "
        f"res = run_episode('Chao-U', 'comm_limited', {run_index}, "
        f"env_seed_for_run({run_index}), fov_radius=5, K=0.5, "
        "grid_size=100, num_agents=6, obstacle_ratio=0.05, "
        "max_steps=10000, chao_variant='bias_cap', comm_range=5.0, "
        "decision='logistic'); "
        "print(json.dumps({'steps_90': res['steps_90'], "
        "'censored': bool(res['censored']), "
        "'sat_frac': res['alpha_sat_frac'], "
        "'fus': res['fusion_events'], 'cov': res['final_coverage']}))"
    )
    out = subprocess.run([sys.executable, "-c", code],
                         capture_output=True, text=True, cwd=V3_DIR)
    if out.returncode != 0:
        raise RuntimeError(f"v3 subprocess failed: {out.stderr}")
    return json.loads(out.stdout.strip().splitlines()[-1])
